import type { SinalizacaoTipo } from '../types/sinalizacaoTipo'

export const tiposSinalizacao: SinalizacaoTipo[] = [
  { id: 'r1-pare', codigo: 'R1', nome: 'Pare', categoria: 'Vertical', grupo: 'Regulamentação', popular: true, ativo: true },
  { id: 'r2-de-preferencia', codigo: 'R2', nome: 'Dê a preferência', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r3-sentido-proibido', codigo: 'R3', nome: 'Sentido proibido', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r4a-proibido-virar-esquerda', codigo: 'R4a', nome: 'Proibido virar à esquerda', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r4b-proibido-virar-direita', codigo: 'R4b', nome: 'Proibido virar à direita', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r5a-proibido-retornar-esquerda', codigo: 'R5a', nome: 'Proibido retornar à esquerda', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r5b-proibido-retornar-direita', codigo: 'R5b', nome: 'Proibido retornar à direita', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r6a-proibido-estacionar', codigo: 'R6a', nome: 'Proibido estacionar', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r6b-estacionamento-regulamentado', codigo: 'R6b', nome: 'Estacionamento regulamentado', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r6c-proibido-parar-estacionar', codigo: 'R6c', nome: 'Proibido parar e estacionar', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r7-proibido-ultrapassar', codigo: 'R7', nome: 'Proibido ultrapassar', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r8a-proibido-mudar-faixa-esquerda', codigo: 'R8a', nome: 'Proibido mudar de faixa para a esquerda', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r8b-proibido-mudar-faixa-direita', codigo: 'R8b', nome: 'Proibido mudar de faixa para a direita', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r9-proibido-caminhoes', codigo: 'R9', nome: 'Proibido trânsito de caminhões', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r10-proibido-veiculos-automotores', codigo: 'R10', nome: 'Proibido trânsito de veículos automotores', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r11-proibido-veiculos-tracao-animal', codigo: 'R11', nome: 'Proibido trânsito de veículos de tração animal', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r12-proibido-bicicletas', codigo: 'R12', nome: 'Proibido trânsito de bicicletas', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r13-proibido-tratores', codigo: 'R13', nome: 'Proibido trânsito de tratores e máquinas de obras', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r14-peso-bruto-maximo', codigo: 'R14', nome: 'Peso bruto total máximo permitido', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r15-altura-maxima', codigo: 'R15', nome: 'Altura máxima permitida', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r16-largura-maxima', codigo: 'R16', nome: 'Largura máxima permitida', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r17-peso-eixo-maximo', codigo: 'R17', nome: 'Peso máximo permitido por eixo', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r18-comprimento-maximo', codigo: 'R18', nome: 'Comprimento máximo permitido', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r19-velocidade', codigo: 'R19', nome: 'Velocidade máxima permitida', categoria: 'Vertical', grupo: 'Regulamentação', popular: true, ativo: true },
  { id: 'r20-proibido-buzina', codigo: 'R20', nome: 'Proibido acionar buzina ou sinal sonoro', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r21-alfandega', codigo: 'R21', nome: 'Alfândega', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r22-corrente-obrigatoria', codigo: 'R22', nome: 'Uso obrigatório de corrente', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r23-conserve-direita', codigo: 'R23', nome: 'Conserve-se à direita', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r24a-sentido-circulacao', codigo: 'R24a', nome: 'Sentido de circulação da via ou pista', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r24b-passagem-obrigatoria', codigo: 'R24b', nome: 'Passagem obrigatória', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r25a-vire-esquerda', codigo: 'R25a', nome: 'Vire à esquerda', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r25b-vire-direita', codigo: 'R25b', nome: 'Vire à direita', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r25c-siga-frente-esquerda', codigo: 'R25c', nome: 'Siga em frente ou à esquerda', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r25d-siga-frente-direita', codigo: 'R25d', nome: 'Siga em frente ou à direita', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r26-siga-frente', codigo: 'R26', nome: 'Siga em frente', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r27-onibus-caminhoes-direita', codigo: 'R27', nome: 'Ônibus, caminhões e veículos de grande porte mantenham-se à direita', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r28-duplo-sentido', codigo: 'R28', nome: 'Duplo sentido de circulação', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r29-proibido-pedestres', codigo: 'R29', nome: 'Proibido trânsito de pedestres', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r30-pedestre-esquerda', codigo: 'R30', nome: 'Pedestre, ande pela esquerda', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r31-pedestre-direita', codigo: 'R31', nome: 'Pedestre, ande pela direita', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r32-circulacao-exclusiva-onibus', codigo: 'R32', nome: 'Circulação exclusiva de ônibus', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r33-circulacao-rotatoria', codigo: 'R33', nome: 'Sentido de circulação na rotatória', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r34-ciclista-esquerda', codigo: 'R34', nome: 'Ciclista, transite à esquerda', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r35a-ciclista-direita', codigo: 'R35a', nome: 'Ciclista, transite à direita', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r36a-ciclistas-esquerda-pedestres-direita', codigo: 'R36a', nome: 'Ciclistas à esquerda, pedestres à direita', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r36b-pedestres-esquerda-ciclistas-direita', codigo: 'R36b', nome: 'Pedestres à esquerda, ciclistas à direita', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r37-proibido-motocicletas', codigo: 'R37', nome: 'Proibido trânsito de motocicletas, motonetas e ciclomotores', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r38-proibido-onibus', codigo: 'R38', nome: 'Proibido trânsito de ônibus', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r39-circulacao-exclusiva-caminhao', codigo: 'R39', nome: 'Circulação exclusiva de caminhão', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },
  { id: 'r40-proibido-carros-mao', codigo: 'R40', nome: 'Trânsito proibido a carros de mão', categoria: 'Vertical', grupo: 'Regulamentação', popular: false, ativo: true },

  { id: 'a1a-curva-acentuada-esquerda', codigo: 'A1a', nome: 'Curva acentuada à esquerda', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a1b-curva-acentuada-direita', codigo: 'A1b', nome: 'Curva acentuada à direita', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a2a-curva-esquerda', codigo: 'A2a', nome: 'Curva à esquerda', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a2b-curva-direita', codigo: 'A2b', nome: 'Curva à direita', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a3a-pista-sinuosa-esquerda', codigo: 'A3a', nome: 'Pista sinuosa à esquerda', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a3b-pista-sinuosa-direita', codigo: 'A3b', nome: 'Pista sinuosa à direita', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a4a-curva-acentuada-s', codigo: 'A4a', nome: 'Curva acentuada em S à esquerda', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a4b-curva-acentuada-s', codigo: 'A4b', nome: 'Curva acentuada em S à direita', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a5a-curva-s', codigo: 'A5a', nome: 'Curva em S à esquerda', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a5b-curva-s', codigo: 'A5b', nome: 'Curva em S à direita', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a6-cruzamento-vias', codigo: 'A6', nome: 'Cruzamento de vias', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a7a-via-lateral-esquerda', codigo: 'A7a', nome: 'Via lateral à esquerda', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a7b-via-lateral-direita', codigo: 'A7b', nome: 'Via lateral à direita', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a8-intersecao-t', codigo: 'A8', nome: 'Interseção em T', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a9-bifurcacao-y', codigo: 'A9', nome: 'Bifurcação em Y', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a10a-entroncamento-esquerda', codigo: 'A10a', nome: 'Entroncamento oblíquo à esquerda', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a10b-entroncamento-direita', codigo: 'A10b', nome: 'Entroncamento oblíquo à direita', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a11a-juncoes-contrarias-esquerda', codigo: 'A11a', nome: 'Junções sucessivas contrárias, primeira à esquerda', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a11b-juncoes-contrarias-direita', codigo: 'A11b', nome: 'Junções sucessivas contrárias, primeira à direita', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a12-intersecao-circulo', codigo: 'A12', nome: 'Interseção em círculo', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a13a-confluencia-esquerda', codigo: 'A13a', nome: 'Confluência à esquerda', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a13b-confluencia-direita', codigo: 'A13b', nome: 'Confluência à direita', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a14-semaforo-frente', codigo: 'A14', nome: 'Semáforo à frente', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a15-parada-obrigatoria-frente', codigo: 'A15', nome: 'Parada obrigatória à frente', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a16-bonde', codigo: 'A16', nome: 'Bonde', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a17-pista-irregular', codigo: 'A17', nome: 'Pista irregular', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a18-lombada', codigo: 'A18', nome: 'Lombada', categoria: 'Vertical', grupo: 'Advertência', popular: true, ativo: true },
  { id: 'a19-depressao', codigo: 'A19', nome: 'Depressão', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a20a-declive-acentuado', codigo: 'A20a', nome: 'Declive acentuado', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a20b-aclive-acentuado', codigo: 'A20b', nome: 'Aclive acentuado', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a21a-estreitamento-pista-centro', codigo: 'A21a', nome: 'Estreitamento de pista ao centro', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a21b-estreitamento-pista-esquerda', codigo: 'A21b', nome: 'Estreitamento de pista à esquerda', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a21c-estreitamento-pista-direita', codigo: 'A21c', nome: 'Estreitamento de pista à direita', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a22-ponte-estreita', codigo: 'A22', nome: 'Ponte estreita', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a23-ponte-movel', codigo: 'A23', nome: 'Ponte móvel', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a24-obras', codigo: 'A24', nome: 'Obras', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a25-mao-dupla-adiante', codigo: 'A25', nome: 'Mão dupla adiante', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a26a-sentido-unico', codigo: 'A26a', nome: 'Sentido único', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a26b-sentido-duplo', codigo: 'A26b', nome: 'Sentido duplo', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a27-area-com-desmoronamento', codigo: 'A27', nome: 'Área com desmoronamento', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a28-pista-escorregadia', codigo: 'A28', nome: 'Pista escorregadia', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a29-projecao-cascalho', codigo: 'A29', nome: 'Projeção de cascalho', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a30a-transito-ciclistas', codigo: 'A30a', nome: 'Trânsito de ciclistas', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a30b-passagem-sinalizada-ciclistas', codigo: 'A30b', nome: 'Passagem sinalizada de ciclistas', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a30c-travessia-compartilhada', codigo: 'A30c', nome: 'Trânsito compartilhado por ciclistas e pedestres', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a31-maquinas-agricolas', codigo: 'A31', nome: 'Trânsito de tratores ou maquinaria agrícola', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a32a-transito-pedestres', codigo: 'A32a', nome: 'Trânsito de pedestres', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a32b-passagem-pedestres', codigo: 'A32b', nome: 'Passagem sinalizada de pedestres', categoria: 'Vertical', grupo: 'Advertência', popular: true, ativo: true },
  { id: 'a33a-area-escolar', codigo: 'A33a', nome: 'Área escolar', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a33b-passagem-escolar', codigo: 'A33b', nome: 'Passagem sinalizada de escolares', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a34-criancas', codigo: 'A34', nome: 'Crianças', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a35-animais', codigo: 'A35', nome: 'Animais', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a36-animais-selvagens', codigo: 'A36', nome: 'Animais selvagens', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a37-altura-limitada', codigo: 'A37', nome: 'Altura limitada', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a38-largura-limitada', codigo: 'A38', nome: 'Largura limitada', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a39-passagem-nivel-sem-barreira', codigo: 'A39', nome: 'Passagem de nível sem barreira', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a40-passagem-nivel-com-barreira', codigo: 'A40', nome: 'Passagem de nível com barreira', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a41-cruz-santo-andre', codigo: 'A41', nome: 'Cruz de Santo André', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a42a-inicio-pista-dupla', codigo: 'A42a', nome: 'Início de pista dupla', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a42b-fim-pista-dupla', codigo: 'A42b', nome: 'Fim de pista dupla', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a42c-pista-dividida', codigo: 'A42c', nome: 'Pista dividida', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a43-aeroporto', codigo: 'A43', nome: 'Aeroporto', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a44-vento-lateral', codigo: 'A44', nome: 'Vento lateral', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },
  { id: 'a45-rua-sem-saida', codigo: 'A45', nome: 'Rua sem saída', categoria: 'Vertical', grupo: 'Advertência', popular: false, ativo: true },

  { id: 'lfo-linha-divisoria-fluxos-opostos', codigo: 'LFO', nome: 'Linha divisória de fluxos opostos', categoria: 'Horizontal', grupo: 'Marcas longitudinais', popular: true, ativo: true },
  { id: 'lms-linha-divisoria-mesmo-sentido', codigo: 'LMS', nome: 'Linha divisória de fluxos de mesmo sentido', categoria: 'Horizontal', grupo: 'Marcas longitudinais', popular: false, ativo: true },
  { id: 'lbo-linha-bordo', codigo: 'LBO', nome: 'Linha de bordo', categoria: 'Horizontal', grupo: 'Marcas longitudinais', popular: true, ativo: true },
  { id: 'lco-linha-continuidade', codigo: 'LCO', nome: 'Linha de continuidade', categoria: 'Horizontal', grupo: 'Marcas longitudinais', popular: false, ativo: true },
  { id: 'mcc-marca-canalizacao', codigo: 'MCC', nome: 'Marca de canalização', categoria: 'Horizontal', grupo: 'Marcas de canalização', popular: false, ativo: true },
  { id: 'zbr-zebrado', codigo: 'ZBR', nome: 'Zebrado de preenchimento da área de pavimento não utilizável', categoria: 'Horizontal', grupo: 'Marcas de canalização', popular: false, ativo: true },
  { id: 'lre-linha-retencao', codigo: 'LRE', nome: 'Linha de retenção', categoria: 'Horizontal', grupo: 'Marcas transversais', popular: false, ativo: true },
  { id: 'lpe-linha-estimulo-reducao-velocidade', codigo: 'LPE', nome: 'Linha de estímulo à redução de velocidade', categoria: 'Horizontal', grupo: 'Marcas transversais', popular: false, ativo: true },
  { id: 'ftp-faixa-travessia-pedestres', codigo: 'FTP', nome: 'Faixa de travessia de pedestres', categoria: 'Horizontal', grupo: 'Marcas transversais', popular: true, ativo: true },
  { id: 'ftc-faixa-travessia-ciclistas', codigo: 'FTC', nome: 'Faixa de travessia de ciclistas', categoria: 'Horizontal', grupo: 'Marcas transversais', popular: false, ativo: true },
  { id: 'mccruz-marcacao-cruzamento-rodocicloviario', codigo: 'MCCruz', nome: 'Marcação de cruzamento rodocicloviário', categoria: 'Horizontal', grupo: 'Marcas transversais', popular: false, ativo: true },
  { id: 'mlp-marca-local-parada', codigo: 'MLP', nome: 'Marca de local de parada de veículos', categoria: 'Horizontal', grupo: 'Marcas transversais', popular: false, ativo: true },
  { id: 'mve-marca-vaga-estacionamento', codigo: 'MVE', nome: 'Marca delimitadora de estacionamento regulamentado', categoria: 'Horizontal', grupo: 'Marcas de estacionamento', popular: false, ativo: true },
  { id: 'mci-marca-controle-intersecao', codigo: 'MCI', nome: 'Marcação de área de conflito em interseção', categoria: 'Horizontal', grupo: 'Marcas de controle', popular: false, ativo: true },
  { id: 'seta-direcional', codigo: 'SETA', nome: 'Seta direcional', categoria: 'Horizontal', grupo: 'Inscrições no pavimento', popular: true, ativo: true },
  { id: 'simbolo-bicicleta', codigo: 'BICI', nome: 'Símbolo indicativo de via, pista ou faixa de trânsito de ciclistas', categoria: 'Horizontal', grupo: 'Inscrições no pavimento', popular: false, ativo: true },
  { id: 'simbolo-deficiente', codigo: 'DEF', nome: 'Símbolo indicativo de vaga para pessoa com deficiência', categoria: 'Horizontal', grupo: 'Inscrições no pavimento', popular: false, ativo: true },
  { id: 'legenda-pare-solo', codigo: 'PARE', nome: 'Legenda PARE no solo', categoria: 'Horizontal', grupo: 'Inscrições no pavimento', popular: true, ativo: true },
  { id: 'legenda-devagar', codigo: 'DEVAGAR', nome: 'Legenda DEVAGAR', categoria: 'Horizontal', grupo: 'Inscrições no pavimento', popular: false, ativo: true },
  { id: 'legenda-onibus', codigo: 'ÔNIBUS', nome: 'Legenda ÔNIBUS', categoria: 'Horizontal', grupo: 'Inscrições no pavimento', popular: false, ativo: true },
]

export const condicoesSinalizacao = [
  { id: 'boa', nome: 'Boa' },
  { id: 'regular', nome: 'Regular' },
  { id: 'danificada', nome: 'Danificada' },
  { id: 'ausente', nome: 'Ausente' },
  { id: 'necessita_manutencao', nome: 'Necessita manutenção' },
]

export const condicoesNumericas = Array.from({ length: 6 }, (_, nota) => {
  const hue = Math.round((nota / 5) * 120)

  return {
    nota,
    label:
      nota === 0
        ? 'Ausente'
        : nota <= 1
          ? 'Crítica'
          : nota <= 3
            ? 'Regular'
            : nota <= 4
              ? 'Boa'
              : 'Excelente',
    color: `hsl(${hue} 72% 43%)`,
  }
})
